"""empty message

Revision ID: 17b225240124
Revises: 97a91cc3bdbb
Create Date: 2025-10-29 20:22:43.485669

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "17b225240124"
down_revision: Union[str, Sequence[str], None] = "97a91cc3bdbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
