"""empty message

Revision ID: 5337d33dcb08
Revises: 7f89aef34d78
Create Date: 2025-10-28 15:41:46.217619

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5337d33dcb08"
down_revision: Union[str, Sequence[str], None] = "7f89aef34d78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
