"""empty message

Revision ID: 7e4301f086f5
Revises: a3770628909d
Create Date: 2025-10-23 19:20:52.225698

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e4301f086f5"
down_revision: Union[str, Sequence[str], None] = "a3770628909d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videojob", "input_video_path", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videojob", "input_video_path", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
