"""empty message

Revision ID: 903418cfffb1
Revises: 188c5730faa7
Create Date: 2025-11-13 19:55:28.912886

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "903418cfffb1"
down_revision: Union[str, Sequence[str], None] = "188c5730faa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
