"""empty message

Revision ID: b3c55e9f1c41
Revises: dcc12d640ce3
Create Date: 2025-11-05 16:47:37.645299

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b3c55e9f1c41"
down_revision: Union[str, Sequence[str], None] = "dcc12d640ce3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
