"""empty message

Revision ID: dcc12d640ce3
Revises: 9828d4e1724b
Create Date: 2025-11-05 09:11:50.972388

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dcc12d640ce3"
down_revision: Union[str, Sequence[str], None] = "9828d4e1724b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
