"""empty message

Revision ID: df512fd9c711
Revises: dd85faeb9c57
Create Date: 2025-10-19 15:49:36.140750

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "df512fd9c711"
down_revision: Union[str, Sequence[str], None] = "dd85faeb9c57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
